import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Menu from '../components/base/Menu';
import PhoneMenu from '../components/ui/PhoneMenu';
import Footer from '../components/base/Footer'

const robotoRegular = localFont({
	src: "./fonts/Roboto-Regular.ttf",
	variable: "--font-roboto-regular",
	weight: "400",
});

const robotoMedium = localFont({
	src: "./fonts/Roboto-Medium.ttf",
	variable: "--font-roboto-medium",
	weight: "500",
});

const robotoBold = localFont({
	src: "./fonts/Roboto-Bold.ttf",
	variable: "--font-roboto-bold",
	weight: "700",
});

const robotoBlack = localFont({
	src: "./fonts/Roboto-Black.ttf",
	variable: "--font-roboto-black",
	weight: "900",
});

export const metadata: Metadata = {
	title: "TVOЁ",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body className={`${robotoRegular.variable} ${robotoMedium.variable} ${robotoBold.variable} ${robotoBlack.variable}`}>
				<Menu />
				<PhoneMenu />
				{children}
				<Footer />
			</body>
		</html>
	);
}
